client_host: 127.0.0.1
client_udp_port: 12347
client_tcp_port: 12348
server_host: 127.0.0.1
server_udp_port: 12345
server_tcp_port: 12346
ball_radius: 75
ball_color: red
ball_spawn_x: 100
ball_spawn_y: 100